# Generated by Django 6.0.2 on 2026-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('company_id', models.TextField(blank=True, help_text='Odoo Many2one: res.company', null=True)),
                ('parent_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.department', null=True)),
                ('child_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('manager_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.employee', null=True)),
                ('member_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('jobs_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('color', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.TextField(blank=True, help_text='Odoo Many2one: res.users', null=True)),
                ('active', models.BooleanField(default=False)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('ssnid', models.CharField(blank=True, max_length=255, null=True)),
                ('sinid', models.CharField(blank=True, max_length=255, null=True)),
                ('identification_id', models.CharField(blank=True, max_length=255, null=True)),
                ('passport_id', models.CharField(blank=True, max_length=255, null=True)),
                ('permit_no', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_no', models.CharField(blank=True, max_length=255, null=True)),
                ('visa_expire', models.DateField(blank=True, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('work_email', models.CharField(blank=True, max_length=255, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.job', null=True)),
                ('department_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.department', null=True)),
                ('parent_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.employee', null=True)),
                ('child_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('coach_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.employee', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('color', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.IntegerField(default=0)),
                ('employee_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('department_id', models.TextField(blank=True, help_text='Odoo Many2one: hr.department', null=True)),
                ('company_id', models.TextField(blank=True, help_text='Odoo Many2one: res.company', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
            ],
        ),
    ]
