# Generated by Django 6.0.2 on 2026-02-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.TextField(blank=True, help_text='Odoo Many2one: crm.lead', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_action_last', models.DateTimeField(blank=True, null=True)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.TextField(blank=True, help_text='Odoo Many2one: crm.team', null=True)),
                ('kanban_state', models.CharField(blank=True, max_length=50, null=True)),
                ('email_cc', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('tag_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, help_text='Odoo Many2one: res.users', null=True)),
                ('referred', models.CharField(blank=True, max_length=255, null=True)),
                ('date_open', models.DateTimeField(blank=True, null=True)),
                ('day_open', models.FloatField(default=0.0)),
                ('day_close', models.FloatField(default=0.0)),
                ('date_last_stage_update', models.DateTimeField(blank=True, null=True)),
                ('date_conversion', models.DateTimeField(blank=True, null=True)),
                ('message_bounce', models.IntegerField(default=0)),
                ('probability', models.FloatField(default=0.0)),
                ('planned_revenue', models.FloatField(default=0.0)),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('color', models.IntegerField(default=0)),
                ('partner_address_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_address_email', models.CharField(blank=True, max_length=255, null=True)),
                ('company_currency', models.TextField(blank=True, help_text='Odoo Many2one: Currency', null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_login', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('street2', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_id', models.TextField(blank=True, help_text='Odoo Many2one: res.country.state', null=True)),
                ('country_id', models.TextField(blank=True, help_text='Odoo Many2one: res.country', null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, help_text='Odoo Many2one: res.partner.title', null=True)),
                ('company_id', models.TextField(blank=True, help_text='Odoo Many2one: res.company', null=True)),
                ('meeting_count', models.IntegerField(default=0)),
                ('lost_reason', models.TextField(blank=True, help_text='Odoo Many2one: crm.lost.reason', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.TextField(blank=True, help_text='Odoo Many2one: crm.team', null=True)),
                ('opportunity_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('meeting_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('opportunity_count', models.IntegerField(default=0)),
                ('meeting_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlannerCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('probability', models.FloatField(default=0.0)),
                ('on_change', models.BooleanField(default=False)),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_leads', models.BooleanField(default=False)),
                ('use_opportunities', models.BooleanField(default=False)),
                ('alias_id', models.TextField(blank=True, help_text='Odoo Many2one: mail.alias', null=True)),
                ('dashboard_graph_model', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sales_won', models.IntegerField(default=0)),
                ('target_sales_done', models.IntegerField(default=0)),
            ],
        ),
    ]
