# Generated by Django 6.0.2 on 2026-02-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAnalyticLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_line', models.TextField(blank=True, help_text='Odoo Many2one: sale.order.line', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.TextField(blank=True, help_text='Odoo Many2one: crm.team', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_category_id', models.TextField(blank=True, help_text='Odoo Many2one: sale.layout_category', null=True)),
                ('layout_category_sequence', models.IntegerField(default=0)),
                ('price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CrmTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_invoices', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IrModelFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_line_warn', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_line_warn_msg', models.TextField(blank=True, null=True)),
                ('sales_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ResCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_count', models.IntegerField(default=0)),
                ('sale_order_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('sale_warn', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_warn_msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleLayoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('subtotal', models.BooleanField(default=False)),
                ('pagebreak', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(blank=True, help_text='Odoo Many2one: sale.order', null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('invoice_lines', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('price_unit', models.FloatField(default=0.0)),
                ('price_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('price_tax', models.FloatField(default=0.0)),
                ('price_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('price_reduce', models.FloatField(default=0.0)),
                ('tax_id', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('price_reduce_taxinc', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('price_reduce_taxexcl', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('discount', models.FloatField(default=0.0)),
                ('product_id', models.TextField(blank=True, help_text='Odoo Many2one: product.product', null=True)),
                ('product_updatable', models.BooleanField(default=False)),
                ('product_uom_qty', models.FloatField(default=0.0)),
                ('product_uom', models.TextField(blank=True, help_text='Odoo Many2one: product.uom', null=True)),
                ('product_image', models.BinaryField(blank=True, null=True)),
                ('qty_delivered_updateable', models.BooleanField(default=False)),
                ('qty_delivered', models.FloatField(default=0.0)),
                ('salesman_id', models.TextField(blank=True, help_text='Odoo Many2one: order_id.user_id', null=True)),
                ('currency_id', models.TextField(blank=True, help_text='Odoo Many2one: order_id.currency_id', null=True)),
                ('company_id', models.TextField(blank=True, help_text='Odoo Many2one: order_id.company_id', null=True)),
                ('order_partner_id', models.TextField(blank=True, help_text='Odoo Many2one: order_id.partner_id', null=True)),
                ('analytic_tag_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('amt_to_invoice', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('amt_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('layout_category_id', models.TextField(blank=True, help_text='Odoo Many2one: sale.layout_category', null=True)),
                ('layout_category_sequence', models.IntegerField(default=0)),
            ],
        ),
    ]
