# Generated by Django 6.0.2 on 2026-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MrpBom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('bom_line_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MrpBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_attachments', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MrpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ir_attachment_id', models.TextField(blank=True, help_text='Odoo Many2one: ir.attachment', null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MrpProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tmpl_id', models.TextField(blank=True, help_text='Odoo Many2one: product.template', null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('workorder_count', models.IntegerField(default=0)),
                ('workorder_done_count', models.IntegerField(default=0)),
                ('user_id', models.TextField(blank=True, help_text='Odoo Many2one: res.users', null=True)),
                ('qty_produced', models.FloatField(default=0.0)),
                ('has_moves', models.BooleanField(default=False)),
                ('scrap_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('scrap_count', models.IntegerField(default=0)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('show_final_lots', models.BooleanField(default=False)),
                ('production_location_id', models.TextField(blank=True, help_text='Odoo Many2one: stock.location', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrpProductionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('product_tmpl_id', models.TextField(blank=True, help_text='Odoo Many2one: product.template', null=True)),
                ('product_id', models.TextField(blank=True, help_text='Odoo Many2one: product.product', null=True)),
                ('bom_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.bom', null=True)),
                ('workcenter_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workcenter', null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('routing_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.routing', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrpRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrpRoutingWorkcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('workcenter_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workcenter', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('worksheet', models.BinaryField(blank=True, null=True)),
                ('time_mode_batch', models.IntegerField(default=0)),
                ('time_cycle', models.FloatField(default=0.0)),
                ('workorder_count', models.IntegerField(default=0)),
                ('batch_size', models.FloatField(default=0.0)),
                ('workorder_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrpUnbuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_tracking', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MrpWorkcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('time_efficiency', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.IntegerField(default=0)),
                ('time_start', models.FloatField(default=0.0)),
                ('time_stop', models.FloatField(default=0.0)),
                ('routing_line_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('order_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('workorder_count', models.IntegerField(default=0)),
                ('workorder_ready_count', models.IntegerField(default=0)),
                ('workorder_progress_count', models.IntegerField(default=0)),
                ('workorder_pending_count', models.IntegerField(default=0)),
                ('workorder_late_count', models.IntegerField(default=0)),
                ('time_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('oee', models.FloatField(default=0.0)),
                ('oee_target', models.FloatField(default=0.0)),
                ('performance', models.IntegerField(default=0)),
                ('workcenter_load', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MrpWorkcenterProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workcenter_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workcenter', null=True)),
                ('workorder_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workorder', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MrpWorkcenterProductivityLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('manual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MrpWorkorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_production', models.FloatField(default=0.0)),
                ('qty_remaining', models.FloatField(default=0.0)),
                ('tracking', models.CharField(blank=True, max_length=50, null=True)),
                ('production_messages', models.TextField(blank=True, null=True)),
                ('next_work_order_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workorder', null=True)),
                ('scrap_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('scrap_count', models.IntegerField(default=0)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_count', models.IntegerField(default=0)),
                ('used_in_bom_count', models.IntegerField(default=0)),
                ('mo_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('bom_count', models.IntegerField(default=0)),
                ('used_in_bom_count', models.IntegerField(default=0)),
                ('mo_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PushedFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_production_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.production', null=True)),
                ('active_move_line_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('bom_line_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.bom.line', null=True)),
                ('unit_factor', models.FloatField(default=0.0)),
                ('needs_lots', models.BooleanField(default=False)),
                ('order_finished_lot_ids', models.TextField(blank=True, help_text='Odoo relationship field', null=True)),
                ('finished_lots_exist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.workorder', null=True)),
                ('production_id', models.TextField(blank=True, help_text='Odoo Many2one: mrp.production', null=True)),
                ('lot_produced_id', models.TextField(blank=True, help_text='Odoo Many2one: stock.production.lot', null=True)),
                ('done_wo', models.BooleanField(default=False)),
                ('done_move', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockPickingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StockWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
